# Generated by Django 4.1 on 2022-10-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convertimage',
            old_name='featured_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='convertimage',
            name='converted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
